import StartingCard from "~/components/StartingCards/StartingCard";
import { getServerAuthSession } from "~/server/auth";
import { redirect } from "next/navigation";
import ChatWindow from "~/components/chat/text/ChatWindow";

export default async function HomePage() {
  const session = await getServerAuthSession();
  console.log('session HOME PAGE>>>>>>>>>>>>>>',session);
  return (
      // <div className="max-w-7xl  mx-auto flex flex-col gap-2 my-2">
      //   <StartingCard inputValue="text-tutor" text="Text Conversation Language Tutor" description="Engage in dynamic text-based conversations with our AI language tutor. Dive into a story generated by the bot, answer questions, and improve your language skills through interactive text conversations."/>
      //   <StartingCard inputValue="audio-tutor" text="Story-based Audio Language Tutor" description="Immerse yourself in language learning through audio stories. The bot generates a story, asks questions, and guides you through a conversational journey. Enhance your listening and speaking skills with this unique audio-based language tutor."/>
      //   <StartingCard inputValue="text-correction" text="Text-Based Language Correction Tutor" description="Practice your written communication skills with our Text Correction Conversation feature. Engage in natural text conversations with the bot, and receive instant feedback as it corrects and guides you to improve your language proficiency."/>
      //   <StartingCard inputValue="audio-correction" text="Audio-Based Language Correction Tutor" description="Hone your speaking and listening skills with our Audio Correction Conversation tool. Have verbal interactions with the bot, receive real-time feedback, and refine your pronunciation and language fluency through engaging audio conversations."/>
      // </div>
    //   <div className="container mx-auto rounded-lg shadow-lg my-4">
    //   <div className="flex flex-row justify-between bg-white">
    //     <ChatWindow/>
    //   </div>
    // </div>
    <div>
      
    </div>

  );
}
