import "~/styles/globals.css";
import { Inter } from "next/font/google";
import Script from "next/script";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Script src="https://cdn.lordicon.com/lordicon.js"></Script>
      <body className={`font-sans ${inter.variable} bg-yellow-200 bg-bgImage bg-cover bg-fixed bg-center bg-no-repeat` }>{children}</body>
    </html>
  );
}
